{% set name = "blessed" %}
{% set version = "1.20.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2cdd67f8746e048f00df47a2880f4d6acbcdb399031b604e34ba8f71d5787680

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - __{{ target_os }}
    {% if target_os == 'win' %}
    - jinxed >=0.5.4
    {% endif %}
    - python >=3.8
    - six >=1.9.0
    - wcwidth >=0.1.4

test:
  imports:
    - blessed
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/blessed/
  summary: Easy, practical library for making terminal apps, by providing an elegant, well-documented interface to Colors, Keyboard input, and screen Positioning capabilities.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
    - mattip
