# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "1.49.0"

package:
  name: blessed
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/b/blessed/blessed-${{ version }}.tar.gz
  sha256: a1c5e15c895898b976d85e6c7278496b325bbb4e656794413bf5c1648c9c12c9

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - flit-core >=3.11,<4
    - pip
  run:
    - python >=${{ python_min }}
    - wcwidth >=0.8.1
    - jinxed >=2.1,<3

tests:
  - python:
      imports:
        - blessed
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - python
        - pytest
    files:
      source:
        - tests/
    script:
      content:
        - python -m pytest -vv tests/
      env:
        TEST_QUICK: 1

about:
  summary: Easy, practical library for making terminal apps, by providing an elegant, well-documented interface for Terminals.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/jquast/blessed
  documentation: https://blessed.readthedocs.io

extra:
  recipe-maintainers:
    - mattip
