# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "1.48.0"

package:
  name: blessed
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/b/blessed/blessed-${{ version }}.tar.gz
  sha256: 5ed4c0d40d0121669ef949e4f23465982614eb821bd110d1d5a98ed97dea13d8

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - flit-core >=3.11,<4
    - pip
  run:
    - python >=${{ python_min }}
    - wcwidth >=0.8.1
    - jinxed >=2.1,<3

tests:
  - python:
      imports:
        - blessed
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      env:
        DISPLAY: :1
      content:
        - pip check
        - echo "Test Script Imports for unix and windows Started"
        - if: noarch_platform  != "win"
          then:
            - echo "Test Script Importing blessed and terminal for unix and windows"
            - python -c "from blessed import Terminal; assert Terminal"
            - python -c "assert __import__('blessed').__version__ == '${{ version }}'"
          else:
            - echo "Test Script Importing jinxed, blessed and terminal for windows"
            - python -c "from jinxed import setupterm; assert setupterm"
            - python -c "from blessed import Terminal; assert Terminal"
            - python -c "assert __import__('blessed').__version__ == '${{ version }}'"
        - echo "Test Script Imports for unix and windows Completed"

about:
  summary: Easy, practical library for making terminal apps, by providing an elegant, well-documented interface for Terminals.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/jquast/blessed
  documentation: https://blessed.readthedocs.io

extra:
  recipe-maintainers:
    - mattip
    - hadim
