# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: blessed
  version: "1.21.0"
  python_check_max: 3.13

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/blessed-${{ version }}.tar.gz
  sha256: ece8bbc4758ab9176452f4e3a719d70088eb5739798cd5582c9e05f2a28337ec

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - __${{ noarch_platform }}
    - python >=${{ python_min }}
    - wcwidth >=0.1.4
    - if: noarch_platform == "win"
      then:
        - jinxed >=1.1.0
tests:
  - python:
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*
      imports:
        - blessed
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      env:
        DISPLAY: :1
      content:
        - pip check

about:
  summary: Easy, practical library for making terminal apps, by providing an elegant, well-documented interface to Colors, Keyboard input, and screen Positioning capabilities.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/jquast/blessed

extra:
  recipe-maintainers:
    - mattip
    - hadim
